### ISSUE TITLE
If file rotation is interrupted, then the newest log file may go missing.

### ISSUE THREAD

**Issue by vext01** [vext01/rotee#1]
If `rotate()` is interrupted (e.g. by a signal) then rotee can exit mid-file-rotation, leaving the newest output file absent!

This was reported to me by @reashlin.

Reproducible with:
```
try_repeat 1000 sh -c "rm rotee.* ; timeout 0.5s sh -c 'cat /dev/zero | ./target/debug/rotee -s 16'; ls rotee.0
```

Eventually this will fail because `rotee.0` is absent.

**Comment by vext01** [comment]
Having spoken with @ltratt, his way of thinking is as follows (@ltratt, correct me if I mis-represent your argument):

 - Generally speaking, you can't guarantee that `rotee.0` always exists, as some signals cannot be masked.
 - Therefore why attempt to make that guarantee.
 - It would be better to simply state that the lowest numbered output file is the newest log file, and if `.0` is absent, so be it. It would only be an empty file anyway...

I'm leaning in favour of this reasoning too...

**Comment by ltratt** [comment]
Yes, that's an accurate summary of what I currently think (of course, I might be wrong!).

That said, I did realise one way of possibly reducing the window for `log.0` not to exist. Let's say `log.0` is full. Rather than renaming it *then* opening a new file, open a new file `log.new`, then mv `log.0` to `log.1` and `log.new` to `log.0`. My thinking is that renaming files is probably much quicker than opening them. However, the more log files you have, the greater the chances of being interrupted during the renaming sequencing, so this still isn't a perfect fix and still leaves the possibility of "holes" when one is interrupted (you could e.g. end up with `log.new log.0 log.1 log.3 log.4`).

**Comment by vext01** [comment]
Yeah. I wonder if it's worth the trouble, if the user already knows that `log.0` may not exist (we will document it).

**Comment by reashlin** [comment]
Using `mv`, starting at the "oldest" file first would mean that you never lose data once it has been committed to disk. You may end up with filenames skipping one of the sequence, but they would still be in order.

If I'm streaming large amounts of data and I'm asking it to rotate many files,  need to buffer the incoming data while the `mv` is happening. Personally, if I'm going to `SIGKILL` a process like this, I'd anticipate some recent data loss. But I'd be annoyed at data that's already on disk going missing.

The initial bug report was made as it was jarring that `log.0` did not exist (though I understood it was linked to my SIGKILL). It does make sense that the file would have had no data in it.

**Comment by vext01** [comment]
I spoke to a friend at lunch time and his take on this was a hybrid of my initial reasoning and laurie's:

 - Do what you can to minimise rotation being interrupted (do block signals).
 - Explain to the user what happens if there is an interruption.

**Comment by davmac314** [comment]
> * Do what you can to minimise rotation being interrupted (do block signals).
> 
> * Explain to the user what happens if there is an interruption.

That would be my approach, FWIW. Might as well mask the signals you can (during the rotation operation); if someone uses an actual unignorable KILL then there's nothing you can do about that, but if people are terminating processes that way, they should probably expect some inconsistency.

**Comment by vext01** [comment]
OK, thanks. I'm now leaning towards "minimise surprises, but explain rare surprises" ethos.

Will update the PR later.
